export const suras = [
    ["Аль-Фатиха (Открывающая Книгу)", "https://cdn.islam.global/koran/sura-1-al-fatixa-otkryvaiushhaia-knigu.pdf"],
    ["Аль-Бакара (Корова)", "https://cdn.islam.global/koran/sura-2-al-bakara-korova.pdf"],
    ["Аль-Имран (Семейство Имрана)", "https://cdn.islam.global/koran/sura-3-al-imran-semeistvo-imrana.pdf"],
    ["Ан-Ниса (Женщины)", "https://cdn.islam.global/koran/sura-4-an-nisa-zenshhiny.pdf"],
    ["Аль-Маида (Трапеза)", "https://cdn.islam.global/koran/sura-5-al-maida-trapeza.pdf"],
    ["Аль-Анам (Скот)", "https://cdn.islam.global/koran/sura-6-al-anam-skot.pdf"],
    ["Аль-Араф (Преграды)", "https://cdn.islam.global/koran/sura-7-al-araf-pregrady.pdf"],
    ["Аль-Анфаль (Трофеи)", "https://cdn.islam.global/koran/sura-8-al-anfal-trofei.pdf"],
    ["Ат-Тауба (Покаяние)", "https://cdn.islam.global/koran/sura-9-at-tauba-pokaianie.pdf"],
    ["Йунус (Иона)", "https://cdn.islam.global/koran/sura-10-iunus-iona.pdf"],
    ["Худ (Худ)", "https://cdn.islam.global/koran/sura-11-xud-xud.pdf"],
    ["Йусуф (Юсуф)", "https://cdn.islam.global/koran/sura-12-iusuf-iosif.pdf"],
    ["Ар-Раад (Гром)", "https://cdn.islam.global/koran/sura-13-ar-raad-grom.pdf"],
    ["Ибрахим (Ибрахим)", "https://cdn.islam.global/koran/sura-14-ibraxim-avraam.pdf"],
    ["Аль-Хиджр (Хиджр)", "https://cdn.islam.global/koran/sura-15-al-xidzr-xidzr.pdf"],
    ["Ан-Нахль (Пчела)", "https://cdn.islam.global/koran/sura-16-an-naxl-pcely.pdf"],
    ["Аль-Исра (Ночной Переход)", "https://cdn.islam.global/koran/sura-17-al-isra-nocnoi-perenos.pdf"],
    ["Аль-Кахф (Пещера)", "https://cdn.islam.global/koran/sura-18-al-kaxf-peshhera.pdf"],
    ["Марьям (Мария)", "https://cdn.islam.global/koran/sura-19-mariam-mariia.pdf"],
    ["Та-Ха (Та-Ха)", "https://cdn.islam.global/koran/sura-20-ta-xa-ta-xa.pdf"],
    ["Аль-Анбийа (Пророки)", "https://cdn.islam.global/koran/sura-21-al-anbiia-proroki.pdf"],
    ["Аль-Хаджж (Паломничество)", "https://cdn.islam.global/koran/sura-22-al-xadzz-palomnicestvo.pdf"],
    ["Аль-Муминун (Верующие)", "https://cdn.islam.global/koran/sura-23-al-muminun-veruiushhie.pdf"],
    ["Ан-Нур (Свет)", "https://cdn.islam.global/koran/sura-24-an-nur-svet.pdf"],
    ["Аль-Фуркан (Различение)", "https://cdn.islam.global/koran/sura-25-al-furkan-razlicenie.pdf"],
    ["Аш-Шуара (Поэты)", "https://cdn.islam.global/koran/sura-26-as-suara-poety.pdf"],
    ["Ан-Намл (Муравей)", "https://cdn.islam.global/koran/sura-27-an-naml-muravi.pdf"],
    ["Аль-Касас (Рассказ)", "https://cdn.islam.global/koran/sura-28-al-kasas-rasskaz.pdf"],
    ["Аль-Анкабит (Паук)", "https://cdn.islam.global/koran/sura-29-al-ankabut-pauk.pdf"],
    ["Ар-Рум (Римляне)", "https://cdn.islam.global/koran/sura-30-ar-rum-rimliane.pdf"],
    ["Лукман (Лукман)", "https://cdn.islam.global/koran/sura-31-lukman-lukman.pdf"],
    ["Ас-Саджда (Поклонение)", "https://cdn.islam.global/koran/sura-32-as-sadzda-poklon.pdf"],
    ["Аль-Ахзаб (Объединённые)", "https://cdn.islam.global/koran/sura-33-al-axzab-sonmy.pdf"],
    ["Саба (Саба)", "https://cdn.islam.global/koran/sura-34-saba-saba.pdf"],
    ["Фатир (Творец)", "https://cdn.islam.global/koran/sura-35-fatyr-angely.pdf"],
    ["Ясин (Ясин)", "https://cdn.islam.global/koran/sura-36-iasin-ia-sin.pdf"],
    ["Ас-Саффат (Вереницы)", "https://cdn.islam.global/koran/sura-37-as-saffat-stoiashhie-v-riad.pdf"],
    ["Сад (Сад)", "https://cdn.islam.global/koran/sura-38-sad-sad.pdf"],
    ["Аз-Зумар (Толпы)", "https://cdn.islam.global/koran/sura-39-az-zumar-tolpy.pdf"],
    ["Га́фир (Покровитель)", "https://cdn.islam.global/koran/sura-40-gafir-proshhaiushhii.pdf"],
    ["Фуссилат (Подробно изложено)", "https://cdn.islam.global/koran/sura-41-fussilat-razieiasneny.pdf"],
    ["Аш-Шура (Совет)", "https://cdn.islam.global/koran/sura-42-as-sura-sovet.pdf"],
    ["Аз-Зухруф (Украшения)", "https://cdn.islam.global/koran/sura-43-az-zuxruf-ukraseniia.pdf"],
    ["Ад-Духан (Дым)", "https://cdn.islam.global/koran/sura-44-ad-duxan-dym.pdf"],
    ["Аль-Джасия (Коленопреклонённая)", "https://cdn.islam.global/koran/sura-45-al-dzasiia-kolenopreklonennye.pdf"],
    ["Аль-Ахкаф (Песчаные дюны)", "https://cdn.islam.global/koran/sura-46-al-axkaf-peski.pdf"],
    ["Мухаммад (Мухаммад)", "https://cdn.islam.global/koran/sura-47-muxammad-muxammad.pdf"],
    ["Аль-Фатх (Победа)", "https://cdn.islam.global/koran/sura-48-al-fatx-pobeda.pdf"],
    ["Аль-Худжурат (Комнаты)", "https://cdn.islam.global/koran/sura-49-al-xudzurat-komnaty.pdf"],
    ["Каф (Каф)", "https://cdn.islam.global/koran/sura-50-kaf-kaf.pdf"],
    ["Аз-Зарият (Разбросанные)", "https://cdn.islam.global/koran/sura-51-az-zariiat-rasseivaiushhie.pdf"],
    ["Ат-Тур (Гора)", "https://cdn.islam.global/koran/sura-52-at-tur-gora.pdf"],
    ["Ан-Наджм (Звезда)", "https://cdn.islam.global/koran/sura-53-an-nadzm-zvezda.pdf"],
    ["Аль-Камар (Луна)", "https://cdn.islam.global/koran/sura-54-al-kamar-mesiac.pdf"],
    ["Ар-Рахман (Милосердный)", "https://cdn.islam.global/koran/sura-55-ar-raxman-miloserdnyi.pdf"],
    ["Аль-Вакиа (Происшествие)", "https://cdn.islam.global/koran/sura-56-al-vakia-padaiushhee.pdf"],
    ["Аль-Хадид (Железо)", "https://cdn.islam.global/koran/sura-57-al-xadid-zelezo.pdf"],
    ["Аль-Муджадила (Препирательство)", "https://cdn.islam.global/koran/sura-58-al-mudzadila-prepiratelstvo.pdf"],
    ["Аль-Хашр (Собрание)", "https://cdn.islam.global/koran/sura-59-al-xasr-sobranie.pdf"],
    ["Аль-Мумтахина (Испытуемая)", "https://cdn.islam.global/koran/sura-60-al-mumtaxana-ispytuemaia.pdf"],
    ["Ас-Сафф (Ряды)", "https://cdn.islam.global/koran/sura-61-as-saff-riady.pdf"],
    ["Аль-Джума (Пятница)", "https://cdn.islam.global/koran/sura-62-al-dzuma-piatnica.pdf"],
    ["Аль-Мунафикун (Лицемеры)", "https://cdn.islam.global/koran/sura-63-al-munafikun-licemery.pdf"],
    ["Ат-Тагабун (Взаимное обманчивость)", "https://cdn.islam.global/koran/sura-64-at-tagabun-vzaimnoe-obmanyvanie.pdf"],
    ["Ат-Талак (Расторжение брака)", "https://cdn.islam.global/koran/sura-65-at-talak-razvod.pdf"],
    ["Ат-Тахрим (Запрещение)", "https://cdn.islam.global/koran/sura-66-at-taxrim-zapreshhenie.pdf"],
    ["Аль-Мульк (Власть)", "https://cdn.islam.global/koran/sura-67-al-mulk-vlast.pdf"],
    ["Аль-Калям (Перо)", "https://cdn.islam.global/koran/sura-68-al-kaliam-pismennaia-trost.pdf"],
    ["Аль-Хакка (Истина)", "https://cdn.islam.global/koran/sura-69-al-xakka-neizbeznoe.pdf"],
    ["Аль-Мааридж (Ступени)", "https://cdn.islam.global/koran/sura-70-al-maaridz-stupeni.pdf"],
    ["Нух (Нух)", "https://cdn.islam.global/koran/sura-71-nux-nux.pdf"],
    ["Аль-Джинн (Джинны)", "https://cdn.islam.global/koran/sura-72-al-dzinn-dzinny.pdf"],
    ["Аль-Муззаммил (Обёрнутый)", "https://cdn.islam.global/koran/sura-73-al-muzzammil-zakutavsiisia.pdf"],
    ["Аль-Муддассир (Одеянный)", "https://cdn.islam.global/koran/sura-74-al-muddassir-zavernuvsiisia.pdf"],
    ["Аль-Кийама (Воскресение)", "https://cdn.islam.global/koran/sura-75-al-kiiama-voskresenie.pdf"],
    ["Аль-Инсан (Человек)", "https://cdn.islam.global/koran/sura-76-al-insan-celovek.pdf"],
    ["Аль-Мурсалят (Посылаемые)", "https://cdn.islam.global/koran/sura-77-al-mursaliat-posylaemye.pdf"],
    ["Ан-Наба (Весть)", "https://cdn.islam.global/koran/sura-78-an-naba-vest.pdf"],
    ["Ан-Назиат (Вырывающие)", "https://cdn.islam.global/koran/sura-79-an-naziat-vyryvaiushhie.pdf"],
    ["Абаса (Соглядатай)", "https://cdn.islam.global/koran/sura-80-abasa-naxmurilsia.pdf"],
    ["Ат-Таквир (Скручивание)", "https://cdn.islam.global/koran/sura-81-at-takvir-skrucivanie.pdf"],
    ["Аль-Инфитар (Разделение)", "https://cdn.islam.global/koran/sura-82-al-infitar-raskalyvanie.pdf"],
    ["Аль-Мутаффифин (Обвешивающие)", "https://cdn.islam.global/koran/sura-83-al-mutaffifin-obvesivaiushhie.pdf"],
    ["Аль-Иншикак (Разверзнется)", "https://cdn.islam.global/koran/sura-84-al-insikak-razverznetsia.pdf"],
    ["Аль-Бурудж (Башни)", "https://cdn.islam.global/koran/sura-85-al-burudz-basni.pdf"],
    ["Ат-Тарик (Ночной путник)", "https://cdn.islam.global/koran/sura-86-at-tarik-nocnoi-putnik.pdf"],
    ["Аль-Аля (Всевышний)", "https://cdn.islam.global/koran/sura-87-al-alia-vysocaisii.pdf"],
    ["Аль-Гашия (Покрывающее)", "https://cdn.islam.global/koran/sura-88-al-gasiia-pokryvaiushhee.pdf"],
    ["Аль-Фаджр (Рассвет)", "https://cdn.islam.global/koran/sura-89-al-fadzr-zaria.pdf"],
    ["Аль-Балад (Город)", "https://cdn.islam.global/koran/sura-90-al-balad-gorod.pdf"],
    ["Аш-Шамс (Солнце)", "https://cdn.islam.global/koran/sura-91-as-sams-solnce.pdf"],
    ["Аль-Лайл (Ночь)", "https://cdn.islam.global/koran/sura-92-al-lail-noc.pdf"],
    ["Ад-Духа (Утро)", "https://cdn.islam.global/koran/sura-93-ad-duxa-utro.pdf"],
    ["Аш-Шарх (Раскрытие)", "https://cdn.islam.global/koran/sura-94-as-sarx-raskrytie.pdf"],
    ["Ат-Тин (Смоковница)", "https://cdn.islam.global/koran/sura-95-at-tin-smokovnica.pdf"],
    ["Аль-Алак (Сгусток/Свернувшаяся кровь)", "https://cdn.islam.global/koran/sura-96-al-alak-sgustok.pdf"],
    ["Аль-Қадр (Ночь могущества)", "https://cdn.islam.global/koran/sura-97-al-kadr-mogushhestvo.pdf"],
    ["Аль-Баййина (Ясное доказательство)", "https://cdn.islam.global/koran/sura-98-al-baiiina-iasnoe-znamenie.pdf"],
    ["Аз-Залзаля (Колебание/Землетрясение)", "https://cdn.islam.global/koran/sura-99-az-zalzala-zemletriasenie.pdf"],
    ["Аль-Адият (Гонимые лошади)", "https://cdn.islam.global/koran/sura-100-al-adiiat-skacushhie.pdf"],
    ["Аль-Кари'а (Страшный День)", "https://cdn.islam.global/koran/sura-101-al-karia-porazaiushhee.pdf"],
    ["Ат-Такасур (Соревнующиеся за приумножение)", "https://cdn.islam.global/koran/sura-102-at-takasur-priumnozenie.pdf"],
    ["Аль-Аср (Предвечернее время)", "https://cdn.islam.global/koran/sura-103-al-asr-predvecernee-vremia.pdf"],
    ["Аль-Хумаза (Клеветник)", "https://cdn.islam.global/koran/sura-104-al-xumaza-xulitel.pdf"],
    ["Аль-Филь (Слон)", "https://cdn.islam.global/koran/sura-105-al-fil-slon.pdf"],
    ["Курайш (Курайш)", "https://cdn.islam.global/koran/sura-106-kurais-kuraisity.pdf"],
    ["Аль-Маун (Милость/Малые услуги)", "https://cdn.islam.global/koran/sura-107-al-maun-milostynia.pdf"],
    ["Аль-Каусар (Изобилие)", "https://cdn.islam.global/koran/sura-108-al-kausar-izobilie.pdf"],
    ["Аль-Кафирун (Неверующие)", "https://cdn.islam.global/koran/sura-109-al-kafirun-neveruiushhie.pdf"],
    ["Ан-Наср (Помощь)", "https://cdn.islam.global/koran/sura-110-an-nasr-pomoshh.pdf"],
    ["Аль-Масад (Пальмовая волокна/Верёвки)", "https://cdn.islam.global/koran/sura-111-al-masad-palmovye-volokna.pdf"],
    ["Аль-Ихлас (Искренность/Очищение веры)", "https://cdn.islam.global/koran/sura-112-al-ixlas-ocishhenie-very.pdf"],
    ["Аль-Фаляк (Рассветная заря)", "https://cdn.islam.global/koran/sura-113-al-faliak-rassvet.pdf"],
    ["Ан-Нас (Люди)", "https://cdn.islam.global/koran/sura-114-an-nas-liudi.pdf"],
];
